language: python
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 2.7
      env: TOXENV=flake8

    - python: 3.6
      env: TOXENV=py36

    - python: 3.7
      env: TOXENV=py37
    - python: 3.7
      env: TOXENV=flake8

install: "pip install tox"

script: tox

notifications:
    email: false
